#!/bin/bash

# This script is built around xdotool.
# Its purpose is to activate the browser window, open lastpass,
# copy the password, close lastpass, and paste the password into
# the window that was currently active before the script was ran.
#
# Author: Chris Jones
# Date: Sep 4 2013

### Begin configuration ###
browserClassName="Vimperator"
tabCloseShortcut="d"
lastpassOffsetX=25
lastpassOffsetY=45
passwordOffsetX=-50
passwordOffsetY=70
### End configuration ###

function errorCheck {
  if [[ -z $1 ]]; then
    echo "A search term is required."
    exit 1
  fi
}

function setMouseMode {
  [[ "$1" == "left" ]] && buttonRight=1 || buttonRight=3
  [[ "$1" == "left" ]] && buttonLeft=3 || buttonLeft=1
}

function getCurrentWindowInfo {
  currentWid=$(xdotool getactivewindow)
  browserWid=$(xdotool search "${browserClassName}" | head -1)
}

function calculateCoordinates {
  eval $(xdotool getwindowgeometry --shell $browserWid)
  browserMouseX=$((X + WIDTH - lastpassOffsetX))
  browserMouseY=$((Y + lastpassOffsetY))
}

function activateLastpass {
  xdotool windowactivate --sync $browserWid
  sleep 0.1
  xdotool mousemove --sync --clearmodifiers $browserMouseX $browserMouseY click $buttonLeft
  sleep 0.1
}

function searchPassword {
  xdotool type --clearmodifiers "$1"
  sleep 0.1
}

function copyPassword {
  xdotool mousemove_relative --sync --clearmodifiers -- $passwordOffsetX $passwordOffsetY click $buttonRight
  sleep 0.1
  xdotool key --clearmodifiers Down Down Down Return
}

function pastePassword {
  # Go back to the previous window
  xdotool windowactivate --sync $currentWid
  # Paste the password and press enter
  xdotool key --clearmodifiers --delay 50 ctrl+shift+v Return
}

errorCheck $1
setMouseMode $2
getCurrentWindowInfo
calculateCoordinates
activateLastpass
searchPassword $1
copyPassword
pastePassword
