#!/bin/bash

# This script is built around xdotool.
# Its purpose is to activate the browser window, open lastpass,
# copy the password, close lastpass, and paste the password into
# the window that was currently active before the script was ran.
#
# Author: Chris Jones
# Date: Jan 31 2014

### Begin configuration ###
browserClassName="Vimperator"
### End configuration ###

initialSetup() {
  getCurrentWindowInfo
  calculateCoordinates
}


setMouseMode() {
  [[ "$1" == "left" ]] && buttonRight=1 || buttonRight=3
  [[ "$1" == "left" ]] && buttonLeft=3 || buttonLeft=1
}

getCurrentWindowInfo() {
  currentWid=$(xdotool getactivewindow)
  browserWid=$(xdotool search "${browserClassName}" | head -1)
}

calculateCoordinates() {
  eval "$(xdotool getwindowgeometry --shell "$browserWid")"
  browserMouseX=$((X + WIDTH - lastpassOffsetX))
  browserMouseY=$((Y + lastpassOffsetY))
}

activateFirefox() {
  xdotool windowactivate --sync "$browserWid"
  sleep 0.2
}

openNewTab() {
  xdotool key --clearmodifiers alt+f
  sleep 0.2
  xdotool key --clearmodifiers t
  sleep 0.5
}

loginToPaylocity() {
  xdotool type --clearmodifiers "https://login.paylocity.com/escher/escher_webui/views/login/login.aspx"
  xdotool key --clearmodifiers Return
  sleep 5
  xdotool key --clearmodifiers Return
  sleep 5
}

punchClock() {
  xdotool key --clearmodifiers space
}

reactivateVimperator() {
  xdotool key --clearmodifiers shift+Escape 
}

initialSetup
activateFirefox
openNewTab
loginToPaylocity
punchClock
reactivateVimperator
